[package]
name = "white-balancer"
version = "0.1.0"
authors = ["Warren Galyen <warrengalyen@github.com>"]

[dependencies]
clap = "2.33.3"
image = "0.23.12" 
nalgebra = "0.23.1"
num = "0.3.1"
num-traits = "0.2.14"


